# Generated by Django 5.1.7 on 2025-03-15 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_firstname_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
    ]
