# Generated by Django 5.1.7 on 2025-03-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
