# Generated by Django 5.1.7 on 2025-03-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_number', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=200, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('incorrect_answers', models.CharField(blank=True, max_length=200, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
