# Generated by Django 5.1.7 on 2025-03-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_question_incorrect_answers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_id']},
        ),
    ]
