# Generated by Django 5.1.7 on 2025-03-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_question_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='incorrect_answer',
            new_name='answers',
        ),
    ]
